// Command fixturegen writes a console.db using the REAL Go store and auth
// packages, populating every table, so the Python port can be checked against
// a database an actual Go console would have produced rather than one we
// hand-rolled to match our own expectations.
//
// The Argon2 hash it writes is generated by the Go implementation, which makes
// this fixture the check for phase 5 as well as phase 4.
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"

	"hookguard/web/internal/auth"
	"hookguard/web/internal/store"
)

func main() {
	if len(os.Args) != 3 {
		log.Fatal("usage: fixturegen <db path> <manifest path>")
	}
	dbPath, manifestPath := os.Args[1], os.Args[2]
	_ = os.Remove(dbPath)

	st, err := store.Open(dbPath)
	if err != nil {
		log.Fatalf("open: %v", err)
	}
	defer st.Close()

	const (
		adminEmail  = "Admin@Example.com"
		memberEmail = "member@example.com"
		password    = "correct-horse-battery-staple"
	)
	base := int64(1767225600000) // 2026-01-01T00:00:00Z in unix ms

	hash, err := auth.HashPassword(password)
	if err != nil {
		log.Fatalf("hash: %v", err)
	}
	adminID, err := st.CreateUser(adminEmail, hash, "admin", base)
	if err != nil {
		log.Fatalf("create admin: %v", err)
	}
	memberHash, err := auth.HashPassword("another-passphrase")
	if err != nil {
		log.Fatalf("hash: %v", err)
	}
	memberID, err := st.CreateUser(memberEmail, memberHash, "member", base+1000)
	if err != nil {
		log.Fatalf("create member: %v", err)
	}
	if err := st.SetUserActive(memberID, false); err != nil {
		log.Fatalf("deactivate: %v", err)
	}

	token, tokenHash, err := auth.NewSessionToken()
	if err != nil {
		log.Fatalf("session token: %v", err)
	}
	csrf, err := auth.NewCSRFToken()
	if err != nil {
		log.Fatalf("csrf: %v", err)
	}
	sessID, err := st.CreateSession(store.Session{
		TokenHash:  tokenHash,
		UserID:     adminID,
		CSRFToken:  csrf,
		CreatedAt:  base,
		LastSeenAt: base + 5000,
		ExpiresAt:  base + 86400000,
		IP:         "203.0.113.7",
		UserAgent:  "Mozilla/5.0 (fixture)",
	})
	if err != nil {
		log.Fatalf("session: %v", err)
	}

	endpoints := []store.Endpoint{
		{Path: "/hook/stripe", Provider: "stripe", UpstreamURL: "http://app:8080/stripe",
			ReplayWindow: "5m", SecretEnv: "STRIPE_SECRET", Active: true},
		{Path: "/hook/github", Provider: "github", UpstreamURL: "http://app:8080/github",
			SecretEnv: "GITHUB_SECRET", Active: true},
		{Path: "/hook/paypal", Provider: "paypal", UpstreamURL: "http://app:8080/paypal",
			WebhookID: "WH-FIXTURE-1", Active: false},
	}
	for i := range endpoints {
		endpoints[i].CreatedAt = base
		endpoints[i].UpdatedAt = base
		if _, err := st.CreateEndpoint(endpoints[i]); err != nil {
			log.Fatalf("endpoint %s: %v", endpoints[i].Path, err)
		}
	}

	events := []store.Event{
		{ReceivedAt: base, Path: "/hook/stripe", Provider: "stripe", Verdict: "accepted",
			UpstreamStatus: 200, LatencyMS: 12, BodyBytes: 42, BodySHA256: "aa", RemoteIP: "203.0.113.1"},
		{ReceivedAt: base + 1000, Path: "/hook/stripe", Provider: "stripe", Verdict: "rejected",
			Reason: "signature mismatch", LatencyMS: 3, BodyBytes: 40, BodySHA256: "bb", RemoteIP: "203.0.113.2"},
		{ReceivedAt: base + 2000, Path: "/hook/github", Provider: "github", Verdict: "accepted",
			UpstreamStatus: 202, LatencyMS: 30, BodyBytes: 90, BodySHA256: "cc", RemoteIP: "203.0.113.3"},
		{ReceivedAt: base + 3000, Path: "/hook/github", Provider: "github", Verdict: "rejected",
			Reason: "stale timestamp", LatencyMS: 7, BodyBytes: 91, BodySHA256: "dd", RemoteIP: "203.0.113.4"},
	}
	if err := st.InsertEvents(events); err != nil {
		log.Fatalf("events: %v", err)
	}

	hour := base / 3600000
	if err := st.UpsertRollups([]store.RollupDelta{
		{Hour: hour, Provider: "stripe", Verdict: "accepted", N: 1},
		{Hour: hour, Provider: "stripe", Verdict: "rejected", N: 1},
		{Hour: hour, Provider: "github", Verdict: "accepted", N: 1},
		{Hour: hour, Provider: "github", Verdict: "rejected", N: 1},
	}); err != nil {
		log.Fatalf("rollups: %v", err)
	}

	if err := st.SetRetentionDays(45); err != nil {
		log.Fatalf("retention: %v", err)
	}
	if err := st.SetSetting("fixture_marker", "written-by-go"); err != nil {
		log.Fatalf("setting: %v", err)
	}

	uid := adminID
	for _, e := range []store.AuthEvent{
		{At: base, UserID: &uid, Email: adminEmail, Kind: store.AuthEventUserCreate, IP: "203.0.113.7"},
		{At: base + 100, UserID: &uid, Email: adminEmail, Kind: store.AuthEventLoginOK, IP: "203.0.113.7"},
		{At: base + 200, UserID: nil, Email: "nobody@example.com", Kind: store.AuthEventLoginFail, IP: "198.51.100.9"},
	} {
		if err := st.InsertAuthEvent(e); err != nil {
			log.Fatalf("auth event: %v", err)
		}
	}

	manifest := map[string]any{
		"_comment":       "Written by the Go console's own store and auth packages. See tests/fixtures/README.md.",
		"base_ms":        base,
		"hour":           hour,
		"admin_id":       adminID,
		"admin_email":    adminEmail,
		"admin_password": password,
		"admin_hash":     hash,
		"member_id":      memberID,
		"member_email":   memberEmail,
		"session_id":     sessID,
		"session_token":  token,
		"session_csrf":   csrf,
		"retention_days": 45,
	}
	data, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		log.Fatalf("manifest: %v", err)
	}
	if err := os.WriteFile(manifestPath, append(data, '\n'), 0o644); err != nil {
		log.Fatalf("write manifest: %v", err)
	}
	fmt.Printf("wrote %s and %s\n", dbPath, manifestPath)
}
