"""Phase 1 exit check: the Python core agrees with the Go implementation.

``tests/vectors/core.json`` is generated by ``oracle/vecgen`` from the Go source
carried over in ``oracle/``. Pinning against it is the point -- a round-trip
test (sign, then verify what we just signed) would pass just as happily against
a preimage we had invented, and the two implementations have to interoperate
during the port.
"""

from __future__ import annotations

import base64
import json
from pathlib import Path
from typing import Any

import pytest

from hookguard_core import gatewaysig
from hookguard_core.goduration import (
    GoDurationError,
    parse_go_duration,
    parse_go_duration_ns,
)

VECTORS = json.loads((Path(__file__).parent / "vectors" / "core.json").read_text("utf-8"))


def _sig_cases() -> list[Any]:
    return VECTORS["gatewaysig"]


def _dur_cases() -> list[Any]:
    return VECTORS["goduration"]


def test_vector_file_is_populated() -> None:
    """Guard against a truncated or half-regenerated vector file silently
    turning every parametrized test below into a no-op."""
    assert len(_sig_cases()) >= 90
    assert len(_dur_cases()) >= 30
    rejected = [v for v in _dur_cases() if v["nanos"] is None]
    assert len(rejected) >= 10, "the rejected-input half is what catches a lax parser"


def test_header_names_match_go() -> None:
    assert gatewaysig.HEADER == VECTORS["header"]
    assert gatewaysig.PROVIDER_HEADER == VECTORS["provider_header"]


# --------------------------------------------------------------------------
# Gateway signature
# --------------------------------------------------------------------------


@pytest.mark.parametrize("case", _sig_cases(), ids=lambda c: c["name"])
def test_sign_matches_go(case: dict[str, Any]) -> None:
    """Our hex output is byte-for-byte what Go produced for the same input."""
    got = gatewaysig.sign(
        case["secret"].encode("utf-8"),
        case["provider"],
        base64.b64decode(case["body_b64"]),
    )
    assert got == case["signature"]


@pytest.mark.parametrize("case", _sig_cases(), ids=lambda c: c["name"])
def test_verify_accepts_go_signature(case: dict[str, Any]) -> None:
    """A signature produced by the Go build verifies here."""
    gatewaysig.verify(
        case["secret"].encode("utf-8"),
        case["provider"],
        base64.b64decode(case["body_b64"]),
        case["signature"],
    )


def test_verify_rejects_tampering() -> None:
    """The three things the signature exists to catch. Uses a real Go vector as
    the starting point so this is not testing our own output against itself."""
    case = _sig_cases()[0]
    secret = case["secret"].encode("utf-8")
    body = base64.b64decode(case["body_b64"])
    sig = case["signature"]

    with pytest.raises(gatewaysig.GatewaySignatureError):
        gatewaysig.verify(secret, "some-other-provider", body, sig)

    with pytest.raises(gatewaysig.GatewaySignatureError):
        gatewaysig.verify(secret, case["provider"], body + b"!", sig)

    with pytest.raises(gatewaysig.GatewaySignatureError):
        gatewaysig.verify(b"wrong-secret", case["provider"], body, sig)


@pytest.mark.parametrize(
    "bad",
    [
        "nothex",
        "abc",  # odd length
        "de ad" + "0" * 59,  # bytes.fromhex would skip the space; Go would not
        "",
        "zz" * 32,
    ],
)
def test_verify_rejects_malformed_hex(bad: str) -> None:
    with pytest.raises(gatewaysig.GatewaySignatureError):
        gatewaysig.verify(b"internal", "stripe", b"{}", bad)


# --------------------------------------------------------------------------
# Go durations
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    "case",
    [c for c in _dur_cases() if c["nanos"] is not None],
    ids=lambda c: c["name"],
)
def test_duration_accepted_matches_go(case: dict[str, Any]) -> None:
    assert parse_go_duration_ns(case["input"]) == case["nanos"]


@pytest.mark.parametrize(
    "case",
    [c for c in _dur_cases() if c["nanos"] is None],
    ids=lambda c: c["name"],
)
def test_duration_rejected_by_go_is_rejected_here(case: dict[str, Any]) -> None:
    """The half that matters: anything Go rejects must raise, never return zero.

    A parser that quietly yields 0 for an input it does not understand disables
    the replay-window check while every other test still passes.
    """
    with pytest.raises(GoDurationError):
        parse_go_duration_ns(case["input"])


def test_duration_timedelta_conversion() -> None:
    assert parse_go_duration("5m").total_seconds() == 300.0
    assert parse_go_duration("1h30m").total_seconds() == 5400.0
    assert parse_go_duration("0").total_seconds() == 0.0
    assert parse_go_duration("-5m").total_seconds() == -300.0
    # Sub-microsecond input truncates toward zero rather than rounding away.
    assert parse_go_duration("1ns").total_seconds() == 0.0
    assert parse_go_duration("-1500ns").total_seconds() == -0.000001
