"""Auth primitives, ported from web/internal/auth/*_test.go.

The centrepiece is that a hash generated by the Go build verifies here. That
is what makes an existing console database migrate with no user action -- get
the Argon2 parameters wrong and every user is locked out, silently and all at
once.
"""

from __future__ import annotations

import hashlib
import json
import time
from datetime import UTC, datetime, timedelta
from pathlib import Path

import pytest

from hookguard_console.auth import (
    CSRF_FORM_FIELD,
    CSRF_HEADER,
    MAX_PASSWORD_LEN,
    MIN_PASSWORD_LEN,
    RESET_TOKEN_TTL,
    SESSION_ABSOLUTE_TIMEOUT,
    SESSION_COOKIE_NAME,
    SESSION_IDLE_TIMEOUT,
    Limiter,
    PasswordPolicyError,
    check_csrf,
    dummy_hash,
    hash_password,
    hash_token,
    new_csrf_token,
    new_reset_token,
    new_session_token,
    validate_password,
    verify_password,
)
from hookguard_console.auth.password import (
    ARGON2_HASH_LEN,
    ARGON2_MEMORY_KIB,
    ARGON2_PARALLELISM,
    ARGON2_SALT_LEN,
    ARGON2_TIME_COST,
)

MANIFEST = json.loads(
    (Path(__file__).resolve().parents[1] / "fixtures" / "go-console.json").read_text("utf-8")
)

PASSWORD = "correct-horse-battery-staple"


# --------------------------------------------------------------------------
# The cross-implementation check
# --------------------------------------------------------------------------


def test_a_hash_generated_by_go_verifies_here() -> None:
    """Phase 5's exit check. The hash in the fixture was produced by the Go
    console's own auth package."""
    assert verify_password(MANIFEST["admin_password"], MANIFEST["admin_hash"]) is True


def test_the_go_hash_rejects_a_wrong_password() -> None:
    """Guards against a verify that returns True unconditionally, which would
    make the test above pass for the wrong reason."""
    assert verify_password("not-the-password", MANIFEST["admin_hash"]) is False


def test_the_go_hash_carries_the_documented_parameters() -> None:
    """The schema comment pins these. argon2-cffi's own defaults differ --
    parallelism is 4 there -- so they are set explicitly rather than
    inherited, and this is what would catch that drifting."""
    assert MANIFEST["admin_hash"].startswith("$argon2id$v=19$m=65536,t=3,p=2$")


def test_our_parameters_match_the_go_build() -> None:
    assert (ARGON2_TIME_COST, ARGON2_MEMORY_KIB, ARGON2_PARALLELISM) == (3, 64 * 1024, 2)
    assert (ARGON2_HASH_LEN, ARGON2_SALT_LEN) == (32, 16)


def test_a_hash_we_generate_has_the_same_shape_go_would() -> None:
    """The other direction: Go must be able to verify what we write. The Go
    side of that was confirmed against the real auth package; here we pin the
    encoding so a change would be caught without needing Go present."""
    phc = hash_password(PASSWORD)
    prefix, go_prefix = phc.split("$")[:4], MANIFEST["admin_hash"].split("$")[:4]
    assert prefix == go_prefix


# --------------------------------------------------------------------------
# Password hashing
# --------------------------------------------------------------------------


def test_hash_and_verify_round_trip() -> None:
    phc = hash_password(PASSWORD)
    assert verify_password(PASSWORD, phc) is True
    assert verify_password(PASSWORD + "x", phc) is False


def test_the_salt_is_random_per_hash() -> None:
    """Two users with the same password must not share a hash, or the users
    table leaks who reused a password."""
    assert hash_password(PASSWORD) != hash_password(PASSWORD)


@pytest.mark.parametrize(
    "malformed",
    ["", "not-a-hash", "$argon2id$", "$argon2id$v=19$m=65536,t=3,p=2$onlysalt", "$bcrypt$x$y"],
)
def test_a_malformed_hash_fails_the_login_rather_than_the_request(malformed: str) -> None:
    """A corrupt row in the users table should refuse that login, not raise
    into the handler and 500 the page."""
    assert verify_password(PASSWORD, malformed) is False


def test_verification_uses_the_parameters_in_the_hash_not_ours() -> None:
    """A hash written under different settings -- an older build, or a future
    parameter bump -- must still verify with the right password. That is the
    whole reason the parameters live in the PHC string.

    Asserting only that a foreign hash fails would prove nothing: it fails for
    a dozen reasons. So this generates a genuine hash under deliberately
    different parameters and requires it to VERIFY.
    """
    from argon2 import PasswordHasher, Type

    other = PasswordHasher(
        time_cost=1, memory_cost=8 * 1024, parallelism=1, hash_len=16, salt_len=8, type=Type.ID
    )
    foreign = other.hash(PASSWORD)
    assert foreign.startswith("$argon2id$v=19$m=8192,t=1,p=1$")
    assert foreign.split("$")[3] != hash_password(PASSWORD).split("$")[3], "params must differ"

    assert verify_password(PASSWORD, foreign) is True
    assert verify_password("wrong", foreign) is False


def test_dummy_hash_is_a_real_verifiable_hash() -> None:
    """It exists to make an unknown-email login cost the same as a wrong
    password. A cheap placeholder would defeat that: the timing difference is
    the enumeration oracle."""
    dummy = dummy_hash()
    assert dummy.startswith("$argon2id$")
    assert verify_password("anything", dummy) is False


def test_dummy_hash_is_computed_once() -> None:
    assert dummy_hash() is dummy_hash()


def test_unknown_user_login_costs_about_the_same_as_a_wrong_password() -> None:
    """The point of the dummy hash, measured rather than assumed.

    A generous bound: this asserts the two are within the same order of
    magnitude, not that they are equal. Wall-clock timing on a shared CI
    runner is noisy, and a tight bound here would be a flaky test rather than
    a stronger guarantee.
    """
    real = MANIFEST["admin_hash"]
    dummy = dummy_hash()

    def elapsed(phc: str) -> float:
        start = time.perf_counter()
        verify_password("some-wrong-password", phc)
        return time.perf_counter() - start

    # Warm up, so neither timing pays a one-off import or allocation cost.
    elapsed(real), elapsed(dummy)

    real_t = min(elapsed(real) for _ in range(3))
    dummy_t = min(elapsed(dummy) for _ in range(3))
    ratio = max(real_t, dummy_t) / max(min(real_t, dummy_t), 1e-9)
    assert ratio < 5, f"timings diverge too much: real={real_t:.4f}s dummy={dummy_t:.4f}s"


# --------------------------------------------------------------------------
# Password policy
# --------------------------------------------------------------------------


def test_policy_accepts_a_reasonable_passphrase() -> None:
    validate_password(PASSWORD)


@pytest.mark.parametrize("length", [0, 1, MIN_PASSWORD_LEN - 1])
def test_policy_rejects_short_passwords(length: int) -> None:
    with pytest.raises(PasswordPolicyError, match="at least"):
        validate_password("a" * length)


def test_policy_rejects_overlong_passwords() -> None:
    """An upper bound is not arbitrary: Argon2 cost scales with input, so an
    unbounded password field is a cheap way to make the server do work."""
    with pytest.raises(PasswordPolicyError, match="at most"):
        validate_password("a" * (MAX_PASSWORD_LEN + 1))


def test_policy_boundaries_are_inclusive() -> None:
    validate_password("a" * MIN_PASSWORD_LEN)
    validate_password("a" * MAX_PASSWORD_LEN)


def test_policy_has_no_composition_rules() -> None:
    """Length only, NIST-style. Composition rules push people toward
    predictable substitutions without adding real entropy."""
    validate_password("aaaaaaaaaaaaaaaa")
    validate_password("             ")


# --------------------------------------------------------------------------
# Session tokens
# --------------------------------------------------------------------------


def test_session_token_and_hash_are_consistent() -> None:
    token, digest = new_session_token()
    assert hash_token(token) == digest
    assert digest == hashlib.sha256(token.encode()).digest()


def test_session_tokens_are_unique_and_long_enough() -> None:
    tokens = {new_session_token()[0] for _ in range(50)}
    assert len(tokens) == 50
    # 32 random bytes as unpadded base64url.
    assert all(len(t) == 43 for t in tokens)


def test_the_go_written_session_token_hashes_to_the_stored_value() -> None:
    """Cross-implementation again: Go minted this token and stored its hash.
    A different encoding here would silently invalidate every live session."""
    assert (
        hash_token(MANIFEST["session_token"])
        == hashlib.sha256(MANIFEST["session_token"].encode()).digest()
    )
    assert len(MANIFEST["session_token"]) == 43


def test_token_hash_is_bytes_of_the_expected_width() -> None:
    _, digest = new_session_token()
    assert isinstance(digest, bytes)
    assert len(digest) == 32


def test_session_timeouts() -> None:
    assert SESSION_IDLE_TIMEOUT == timedelta(days=7)
    assert SESSION_ABSOLUTE_TIMEOUT == timedelta(days=30)
    assert SESSION_ABSOLUTE_TIMEOUT > SESSION_IDLE_TIMEOUT
    assert SESSION_COOKIE_NAME == "hg_session"


def test_csrf_tokens_are_unique() -> None:
    assert len({new_csrf_token() for _ in range(50)}) == 50


# --------------------------------------------------------------------------
# CSRF
# --------------------------------------------------------------------------


def test_csrf_matching_token_passes() -> None:
    token = new_csrf_token()
    assert check_csrf(token, token) is True


def test_csrf_mismatched_token_fails() -> None:
    assert check_csrf(new_csrf_token(), new_csrf_token()) is False


@pytest.mark.parametrize(("want", "got"), [("", ""), ("abc", ""), ("", "abc")])
def test_csrf_empty_values_never_match(want: str, got: str) -> None:
    """A missing token is what a forged cross-site request looks like. Plain
    equality would let the empty-vs-empty case straight through."""
    assert check_csrf(want, got) is False


def test_csrf_field_names() -> None:
    assert CSRF_HEADER == "X-CSRF-Token"
    assert CSRF_FORM_FIELD == "csrf_token"


# --------------------------------------------------------------------------
# Reset tokens
# --------------------------------------------------------------------------


def test_reset_token_matches_its_hash() -> None:
    token, digest = new_reset_token()
    assert hash_token(token) == digest


def test_reset_tokens_are_unique() -> None:
    assert len({new_reset_token()[0] for _ in range(50)}) == 50


def test_reset_token_ttl_is_short() -> None:
    assert RESET_TOKEN_TTL == timedelta(hours=1)


# --------------------------------------------------------------------------
# Rate limiting
# --------------------------------------------------------------------------

NOW = datetime(2026, 1, 1, tzinfo=UTC)


def test_allows_up_to_the_limit_then_refuses() -> None:
    limiter = Limiter(3, timedelta(minutes=15))
    for _ in range(3):
        allowed, _ = limiter.allow("a@example.com", NOW)
        assert allowed is True
    allowed, retry_after = limiter.allow("a@example.com", NOW)
    assert allowed is False
    assert retry_after == timedelta(minutes=15)


def test_keys_are_independent() -> None:
    limiter = Limiter(1, timedelta(minutes=15))
    assert limiter.allow("a@example.com", NOW)[0] is True
    assert limiter.allow("b@example.com", NOW)[0] is True
    assert limiter.allow("a@example.com", NOW)[0] is False


def test_the_window_slides_off() -> None:
    limiter = Limiter(2, timedelta(minutes=15))
    limiter.allow("a", NOW)
    limiter.allow("a", NOW)
    assert limiter.allow("a", NOW)[0] is False
    assert limiter.allow("a", NOW + timedelta(minutes=16))[0] is True


def test_retry_after_counts_from_the_oldest_hit() -> None:
    limiter = Limiter(2, timedelta(minutes=15))
    limiter.allow("a", NOW)
    limiter.allow("a", NOW + timedelta(minutes=5))
    _, retry_after = limiter.allow("a", NOW + timedelta(minutes=10))
    assert retry_after == timedelta(minutes=5)


def test_a_refused_attempt_does_not_extend_the_window() -> None:
    """Otherwise an attacker hammering the endpoint keeps the real user locked
    out indefinitely -- the lockout becomes the attack."""
    limiter = Limiter(1, timedelta(minutes=10))
    limiter.allow("a", NOW)
    for minute in range(1, 10):
        limiter.allow("a", NOW + timedelta(minutes=minute))
    assert limiter.allow("a", NOW + timedelta(minutes=11))[0] is True


def test_prune_drops_expired_keys() -> None:
    """The key is attacker-supplied, so an unbounded map is a slow memory leak
    someone can drive."""
    limiter = Limiter(5, timedelta(minutes=15))
    for i in range(100):
        limiter.allow(f"user{i}@example.com", NOW)
    assert limiter.tracked_keys == 100

    assert limiter.prune(NOW + timedelta(minutes=16)) == 100
    assert limiter.tracked_keys == 0


def test_prune_keeps_live_keys() -> None:
    limiter = Limiter(5, timedelta(minutes=15))
    limiter.allow("old", NOW)
    limiter.allow("recent", NOW + timedelta(minutes=14))
    limiter.prune(NOW + timedelta(minutes=16))
    assert limiter.tracked_keys == 1
    # The surviving key keeps its history, so pruning is not a free reset.
    assert limiter.allow("recent", NOW + timedelta(minutes=16))[0] is True


def test_limiter_is_thread_safe() -> None:
    """No race detector in Python, so the concurrent path gets an explicit
    test: N threads against one key must yield exactly `max` allowances."""
    import threading

    limiter = Limiter(50, timedelta(minutes=15))
    results: list[bool] = []
    lock = threading.Lock()

    def hammer() -> None:
        allowed, _ = limiter.allow("shared", NOW)
        with lock:
            results.append(allowed)

    threads = [threading.Thread(target=hammer) for _ in range(200)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()

    assert sum(results) == 50, "the limit must hold exactly under concurrency"
    assert len(results) == 200
